export const courses = [
  {
    id: 1,
    title: "الكورس الشامل في الرياضيات",
    teacher: "أ/أشرف علي",
    image: "/images/courses/math.jpg",
    rating: 4.9,
    students: 1240,
    price: 350,
    badge: "الأكثر طلبًا",
    category: "popular",
  },
  {
    id: 2,
    title: "فيزياء الصف الثالث الثانوي",
    teacher: "أ/ محمد علي",
    image: "/images/courses/physics.jpg",
    rating: 5,
    students: 980,
    price: 400,
    badge: "جديد",
    category: "new",
  },
  {
    id: 3,
    title: "اللغة العربية",
    teacher: "أ/ عبدالله الأبيض",
    image: "/images/courses/arabic.jpg",
    rating: 4.8,
    students: 1500,
    price: 300,
    badge: "الأكثر طلبًا",
    category: "popular",
  },
];